services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anaoi-project
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # Mount SSL certificates
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - anaoi-network

networks:
  anaoi-network:
    driver: bridge
